author: Doug
author_url: https://github.com/dougzilla32
module: CancelForPromiseKit
module_version: 1.0.0
readme: README.md
root_url: https://dougzilla32.github.io/CancelForPromiseKit/api
dash_url: https://dougzilla32.github.io/CancelForPromiseKit/api/docsets/CancelForPromiseKit.xml
github_url: https://github.com/dougzilla32/CancelForPromiseKit
github_file_prefix: https://github.com/dougzilla32/CancelForPromiseKit/tree/master
